### ISSUE TITLE
statamic 4 compatibility

### ISSUE THREAD

**Issue by wnpolzin** [arthurperton/statamic-popular#2]
Hello Arthur,
will the addon also be compatible for statamic 4 in the near future?
Thanks and best regards

**Comment by martinkuzelka** [comment]
Hi Arthur,
same question here. Is there any plan for update?

Thanks for your reply.

**Comment by arthurperton** [comment]
Thanks for the messages, and I do want to look into making it v4 compatible soon.

**Comment by arthurperton** [comment]
Support for Statamic v4 has been added in the most recent release, v1.1.0
