### ISSUE TITLE
Update Badge is indicating an update when Popular Installed (but no update is shown)

### ISSUE THREAD

**Issue by Qeria** [arthurperton/statamic-popular#4]
## Bug description
When installed, the "Popular" add-on the "updates" in the Control Panel appear with a badge indicating an update, however no update is available.

## How to Reproduce
1. Install the "Popular" add-on via composer.
2. Login to the CP
3. A new badge will appear indicating "1" update.
4. When clicked in the "Update" no add-on or system update is shown.

## Extra Detail
<img width="957" alt="Screenshot 2023-10-04 at 11 17 43" src="https://github.com/arthurperton/statamic-popular/assets/648164/c3eb4b9c-99d2-4fa5-b8cf-6fee5aa56c06">
<img width="250" alt="Screenshot 2023-10-04 at 11 17 31" src="https://github.com/arthurperton/statamic-popular/assets/648164/b1400575-03fd-4583-999d-a5cbdeecf6cc">

## Environment
<img width="400" alt="Screenshot 2023-10-04 at 11 19 05" src="https://github.com/arthurperton/statamic-popular/assets/648164/a78579d3-16fc-4458-8c91-933fa76981b2">

**Statamic version:** 4.24.0

**PHP version:** 8.2.9

**Addon version:** 1.1.0

**Install method for Statamic (choose one):**
- Fresh install from `statamic/statamic`
- Starter kit (Peak)

**Comment by arthurperton** [comment]
Thank you for reporting this. Somehow there seemed to be some confusion in GitHub about which version was the latest. I resolved that by explicitly setting the most recent version (v1.1.0) as the latest version. Closing the issue now. If you keep having this problem though feel free to reopen.
